model:
  name: vit_heatmap
  backbone: vit_base_patch16_224
  num_landmarks: 5

data:
  train_csv: datasets/lumbar/splits/train.csv
  val_csv: datasets/lumbar/splits/val.csv

  train_image_root: datasets/lumbar/images/train
  val_image_root: datasets/lumbar/images/val

  img_size: [224, 224]


training:
  epochs: 100
  lr: 0.001
  optimizer: adamw
  weight_decay: 0.01
  batch_size: 16
  num_workers: 2
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.3
    patience: 2
    min_lr: 1.0e-6
  early_stopping:
    patience: 6

loss:
  type: smooth_l1
  beta: 0.02

logging:
  save_dir: runs/vit_heatmap
  log_interval: 5
  val_interval: 1